### ISSUE TITLE
Build status icon should allow multiple build definitions

### ISSUE THREAD

**Issue by letmaik** [microsoft/azure-repos-vscode#146]
If a git branch triggered several builds (e.g. Linux and Windows), then currently clicking on the build status icon open a random build. Given that there is no overview page in VSTS for all builds related to a push, the build icon should have a selector for navigating to a specific build, which would also display the build status individually if one of two builds failed for example.

**Comment by jeffyoung** [comment]
Hi @letmaik.  Right now, the items that you can add to the VS Code status bar allow you to do just a few things like set the octicon, add a tooltip and provide a command.  Ideally, you could add additional UI so that, on click, you could show a list of items in a 'fly out' menu (like multiple builds).  Today, that's just not possible.

If I understand well, you've got multiple CI builds that kick off when a push occurs on a certain branch.  The API we use today asks the server to give us the state of the build related to a particular branch and repository.  It's likely that the 'randomness' is related to which build completes first and at what time the build status is requested by the extension.

We can spend some time thinking of other solutions to the issue (perhaps allowing multiple builds to be tracked).

Thanks for the feedback and trying out the extension!

**Comment by Jaykul** [comment]
How about (as a minimum) making the `"team.buildDefinitionId": 0,` setting work even with tfvc -- at least then we could force the one we care about the most?
