### ISSUE TITLE
Included and excluded changes are not persisted when changing folders

### ISSUE THREAD

**Issue by pderks** [microsoft/azure-repos-vscode#181]
**Example folder structure:**
Workspace Root
|---- Project 1
|---- Project 2

**Problem:**
Using the above folder structure as an example. If I open Project 1 in VS Code, move some of the included changes to excluded changes and then open Project 2 in VS Code the changes I moved from included to excluded are now listed back under included changes.

**Expected Behavior:**
If I exclude a file and then open a different folder in VS Code the file excluded should still appear in the excluded files list.

**Comment by jeffyoung** [comment]
Hi @pderks, thanks for trying out the extension (and thanks for the detail)!

Yes, today, the 'excluded' group is simply held in memory since there's no way to inform TFVC to 'exclude' those files at the command line.  The files that are in the included list have had some TFVC command run on them and they're _not_ in the excluded list.  That's why those get persisted (TFVC knows about them).

So I'm sure I understand, you've opened these folders in VS Code (using Open Folder...) correct?  In that case, each time you open the folder the extension is re-initialized (which is by design).  I just want to ensure I understand your scenario.

One thing I had considered was storing some of this state in either `workspaceState` or `globalState` with the [ExtensionContext object](https://code.visualstudio.com/docs/extensionAPI/vscode-api#_a-nameextensioncontextaspan-classcodeitem-id1016extensioncontextspan).  Maybe I could do that at some point.

**Comment by pderks** [comment]
@jeffyoung Yes, that is an accurate description of the scenario. I like your idea of a workspace state or global state. I believe it would be a helpful feature especially when working with multiple projects at the same time.
