### ISSUE TITLE
Workitem is not associated while doing checkin with tf.exe

### ISSUE THREAD

**Issue by fforjan** [microsoft/azure-repos-vscode#191]
When trying to associate work items for checkin, my checkin is rejected:

```
tf checkin -noprompt ******** myproject\.tfignore myproject\.vscode\settings.json -comment:Update tfignore for UILess project  #492455 - Arch - Sprint 3 General Items
[Checkin] TF10139: The following check-in policies have not been satisfied:   The Work Item Query Policy failed because no work items were associated with this check-in.  No files checked in.
```

I've used the associated item and picked one (the #492455 which was added to the comment line) but this is not added.
While reviewing the tf.exe command line, I found this :
https://social.msdn.microsoft.com/Forums/vstudio/en-US/33830525-ede9-48ca-adcf-a8e820b4b3ba/how-to-associate-work-item-information-with-tfexe-checkin-command-?forum=tfsversioncontrol

Which means the current approach is 'broken' for us which requires (MUST HAVE) associated workitems ?

**Comment by jeffyoung** [comment]
Hi @fforjan.  Yes, I should have [known this](https://github.com/Microsoft/vsts-vscode/blob/master/src/tfvc/commands/checkin.ts#L95-L96) (and thanks to the link with the bug report from *2008*!).

While tf.exe doesn't support it (and a few other things like not forcing it to return English strings to parse), the Team Explorer Everywhere Command Line Client (TEE CLC) [does support associating work items](https://github.com/Microsoft/vsts-vscode/blob/master/src/tfvc/commands/checkin.ts#L39-L41).

However, in order to use the TEE CLC on Windows, you need to do the following (this information is taken from the [TFVC_README](https://github.com/Microsoft/vsts-vscode/blob/master/TFVC_README.md); specifically [this](https://github.com/Microsoft/vsts-vscode/blob/master/TFVC_README.md#eclipse-jetbrains-ides-windows-macos-linux)).  (While the TEE CLC is _primarily_ for macOS and Linux users it can also be used on Windows.)

- Download and install a version of [Java 8 for Windows](http://www.oracle.com/technetwork/java/javase/downloads/jre8-downloads-2133155.html).
- Ensure that that path to `java.exe` is a part of your `PATH` environment variable.
  - Mine ends up being set to `C:\ProgramData\Oracle\Java\javapath\`
  - Check that you can successully run `java -version`
- Download and unzip the [TEE CLC](https://github.com/Microsoft/team-explorer-everywhere/releases/download/v14.114.0/TEE-CLC-14.114.0.zip) to a local folder of your choice.
- Open a command prompt and run `{path-to-tf.cmd} eula` and accept the End User License Agreement.
- Update your `tfvc.location` to the full path to `tf.cmd` (e.g., `C:\TEE-CLC-14.111.1\tf.cmd`).
- The last thing that you *have* to do is run the `tf workspaces` command as detailed [here](https://github.com/Microsoft/vsts-vscode/blob/master/TFVC_README.md#i-have-workspaces-created-with-visual-studio-can-i-use-the-tee-clc-to-work-with-them) so that the CLC is aware of the workspaces in the specified collection.  (Each tool, tf.cmd and tf.exe, keeps a local cache of workspaces.)

There's also [a video](https://github.com/Microsoft/vsts-vscode/blob/master/TFVC_README.md#which-instructions-do-i-follow-to-set-up-tfvc-functionality-on-the-macos) that shows how to do this on Linux (the same high-level steps apply on Windows).

After you do all that, you'll be using the TEE CLC with that workspace. If you put the `tfvc.location` setting in your VS Code *workspace* settings, it will only use it for a particular folder (instead of all folders). That might apply.

So if you're willing to do all of that, you can get associate work items going (to satisfy your checkin policies).

Another option would be for me to provide the ability to bypass the checkin policies (since they're client-side policies) via an extension setting. But then you'd have to go back to the server and do the work item association manually.

Updating tf.exe itself would be a much longer-term solution (but you're already aware that it's been almost 10 years).

Let me know what questions you have (I'd be happy to work through it).

**Comment by fforjan** [comment]
@jeffyoung  I don't want my team to bypass the rule, the scrumm master is not going to be happy and it will raise red line in our project manager report  ;)
I will try it but next week, I'm in personal trip in France for the moment !

**Comment by jeffyoung** [comment]
Hi @fforjan.  I just wanted to check in and see if you were ever able to try this out (and, hopefully, get it working)?

**Comment by fforjan** [comment]
Excluding and Including files is very slow on my computer when using TEE, close to not be usable.
I will record a video and share it with you

**Comment by nukec** [comment]
Have the same issue, is this fixed? This is unusable, if there is requirement to add work item(which should be by default requirement).

**Comment by jeffyoung** [comment]
This issue is particular to TF.exe (as the TEE CLC supports associating work items).  Although I've filed a bug against TF.exe about lacking the support for associating work items for TFVC repositories, the issue has been around a long time (https://social.msdn.microsoft.com/Forums/vstudio/en-US/33830525-ede9-48ca-adcf-a8e820b4b3ba/how-to-associate-work-item-information-with-tfexe-checkin-command-?forum=tfsversioncontrol).  I don't expect TF.exe to be updated anytime soon.

Unfortunately, the only workaround in VS Code that I'm aware of is to the use the TEE CLC (like I described above) which does support associating work items on check-in.  I would expect Visual Studio (the IDE) to be able to do this as I don't believe it uses the TF.exe directly (I believe it uses direct SOAP calls and updates the work items that way).

**Comment by jeffyoung** [comment]
The only other option would be to run `tf checkin` at the command line (perhaps from the VS Code terminal) which should pop UI that would allow the association of work items.  In that way, you'd be using VS Code to make your changes, include and exclude, but would need to interactively run `tf checkin`.

It's certainly unfortunate that TF.exe doesn't support this (and hasn't for a long time).

**Comment by pollusb** [comment]
I resolved this by using team explorer seperatly for the moment.

**Comment by nukec** [comment]
@pollusb erm yeah, well is there any other option. That's work around, not solution hehe. But yeah, still not implemented I guess? @jeffyoung any update on this? Thanks

**Comment by kaylangan** [comment]
@nukec you can type "#<work item ID>" into the commit box directly as a workaround.

**Comment by dfaroi** [comment]
#433

**Comment by StavM** [comment]
Any progress on this issue ? isn't it as simple as adding a configuration key to the _tfsv.settings_ to toggle adding and removing the '-noprompt' key from the TF.exe commands ?

**Comment by serhaton** [comment]
Any update please ?
This is still an issue with version 1.42.1
#12345 does not work either from the comment box.

Thanks

**Comment by tititestor** [comment]
To override checkin policy i have modify checkin.js file .vscode\extensions\ms-vsts.team-1.161.1\out\src\tfvc\commands), and now i can temporaly checkin from vs code

```
GetExeArguments() {
        const builder = new argumentbuilder_1.ArgumentBuilder("checkin", this._serverContext, true /* skipCollectionOption */)
            .AddAll(this._files);
        if (this._comment) {
            builder.AddSwitchWithValue("comment", this.getComment(), false);
	    builder.AddSwitchWithValue("override", "Titi", false);
        }
        // TF.EXE doesn't support associating work items with checkin
        //builder.AddSwitchWithValue("associate", this.getAssociatedWorkItems(), false);
        return builder;
    }
```
Maybe have override setting can be an interesting option

Titi
