### ISSUE TITLE
How do you exclude folders when check-in?

### ISSUE THREAD

**Issue by nukec** [microsoft/azure-repos-vscode#248]
Thanks for this great extension.
I am having an issue with angular solution, where 16000 files are shown in excluded changes, which means every time I exclude some file, it takes forever to reload all excluded change.

In visual studio i used .tfignore, how do you ignore here?

![vscode](https://cloud.githubusercontent.com/assets/3589518/26764838/b0c3e864-4966-11e7-86c3-a7fdd60f1da1.PNG)

**Comment by jeffyoung** [comment]
Hi @nukec.  Thanks for using the extension!

Do you have a .tfignore file in this particular workspace (you mentioned you use them in Visual Studio)?  With a quick test using tf.exe at the command line with a .tfignore file, I was able to successfully ignore files so long as they weren't already a part of the workspace (that is, so long as they weren't already checked in).  If the files are already checked in and they have edits on them, it appears a .tfignore file won't actually ignore them.

Also, if you open the solution in Visual Studio, do you see the same results or are the files ignored?  (I'm asking to attempt to determine if this is a feature of Visual Studio and *not* the TF.exe command line tool that the VS Code extension uses).

**Comment by nukec** [comment]
Hi @jeffyoung .
They are under detected, but are not shown in excluded changes:
![kemper4](https://cloud.githubusercontent.com/assets/3589518/26822351/a20454ee-4aa1-11e7-94e9-4d4feef8e185.PNG)

The .tfignore is in Solution Items folder:
![kemper5](https://cloud.githubusercontent.com/assets/3589518/26822397/c7c2698c-4aa1-11e7-916b-399bc1552233.PNG)

Where in structure in vscode should I put .tfignore file and what should be the content in vscode case, or is it the same as in visual studio?

>  With a quick test using tf.exe at the command line with a .tfignore file,

How did you perform this test?

**Comment by jeffyoung** [comment]
Hi @nukec.

To test the effect of .tfignore, I simply created a .tfignore file and included the file specification that I wanted to ignore (in my case, \*.txt).  I placed that .tfignore file in the root of my repository.  I already had a README.txt file at the root of my repository so I went ahead and created a new one (newfile.txt).  Since README.txt was already under version control, any change I made to it was _not_ ignored (since it's already under version control).  However, after creating newfile.txt, newfile.txt _didn't_ show up and wasn't returned via `tf status` (the extension parses the output of `tf status` to determine what has changed). So it appears that any changes to the .tfignore file will not be applied to files _already under version control_.  In addition, I presume as long as the command line client can detect the .tfignore file (and I believe it just has to be in the workspace), it should be applied.  **What are the contents of your .tfignore?**

In your scenario, the Visual Studio IDE appears to be detecting the 16,000 files as possible changes but does not explicitly show them under 'Excluded Changes' (showing them as 'Detected Changes' instead).  Conversely, the VS Code extension _is_ showing them under 'Excluded Changes' and doesn't categorize them as 'Detected Changes'.  I should be able to detect the difference but will have to investigate whether or not I can forgo showing any 'Detected Changes' in the UI (although I'm not sure I'd want to do that because then you wouldn't have a way to add them 😕; the VS IDE can pop a new dialog which can't be done in VS Code).  Also, since the VS Code extension uses a command line client to detect changes, if you've got 16,000 of them, the extension is going to have to spin through all 16,000 of them each time we take an action (run status, move files between statuses, etc.).  My guess is that the VS IDE does this in-memory (but I'll need to ask around).

Quick question: **are the files in your Excluded changes checked in to your TFVC repository?**  I presume not but wanted to make sure.

**Comment by jeffyoung** [comment]
Hi @nukec.

In additional, here's [some documentation](https://www.visualstudio.com/en-us/docs/tfvc/add-files-server#tfignore) on .tfignore.  Based on what I see, it appears you need to add an entry like `\node_modules`.  That should remove all of the files under node_modules from the viewlet in VS Code as well as greatly reduce the number showing up as 'Detected Changes' in Visual Studio.

I'm interested in knowing more about your .tfignore file and if this suggestion clears things up for you.

**Comment by Mimis40** [comment]
Any news on this? It would be really awesome to have a collapsible section or something to separate excluded changes from detected changes. I have 50,000 files in my excluded section right now.. No way in heck am I going to look through all of those directories to find the file that I actually want to find. This extension is pretty much useless for me until something like this is implemented. 

Currently right now I am making my changes in visual studio code, and then going to visual studio to manage files and commits

**Comment by nukec** [comment]
Still nothing I think.

**Comment by Nehmiabm** [comment]
@Mimis40 I have found a pretty nice trick for this. Follow these two steps;

1. You have to create .tfignorefile.txt file in the root of your workspace and include the files you want to exclude there. (e.g \node_modules). jeffyoung has pretty much explained how to do this so follow his instructions. (Important: Make sure the folder you want to exclude is not checked in TFS)

2. First step will take care of ignoring the file so it won't show up under included changes. But still the files will be displayed under excluded changes right? To get rid of this, go to the location of your folder (e.g c:\workspace\node_modules), right click on 'node_modules', click Properties and change the attribute of the folder to 'Hidden'. Restart vscode and you will see that the ignored folder will no longer be visible under excluded changes.

Let me know if this helped. Good luck :-)

**Comment by nicholasdoyle** [comment]
I am running into this same issue - my .tfignore file is not being recognized by this extension

**Comment by billyjacobs2014** [comment]
So @nicholasdoyle an important thing that I have found while attempting everyone's solutions are the details. The key is where you place the .tfignore file. 

In order to find where the file should go the easiest solution is to use Team Explorer to automatically create the file so that it is placed in the correct directory. I was trying to place mine at the root of my angular project, where my package.json is located but that is not correct if it is not the root of the source control location. In my case the file actually belonged 2 directories up. 

See instructions in this article: Search for this text "Create and use a .tfignore file" (NOTE: It is near the end of the page)
https://docs.microsoft.com/zh-cn/vsts/tfvc/add-files-server?view=vsts#customize-which-files-are-ignored-by-version-control
