### ISSUE TITLE
New Item default to included changes

### ISSUE THREAD

**Issue by 72gm** [microsoft/azure-repos-vscode#284]
When you add a new item it is automatically added to excluded items.

Surely this makes no sense? Can this not default to included items??

**Comment by jeffyoung** [comment]
Items that aren't yet under TFVC control are indeed added as Excluded but this should be consistent with 'Detected Changes' in Visual Studio.  When items are moved to the Included list, the SCM Provider runs 'tf add' on them so that they can be tracked.

Is this behavior not consistent with Local workspaces within Visual Studio?

**Comment by cocowalla** [comment]
In Visual Studio using TFS 2015, new files are automatically included in the list of files to be committed. In VS Code, they are not, so I keep checking code in with missing files :(

Is there some way to make this configurable, such that new files must be explicitly *excluded* rather than *included*?

**Comment by ScottAHoward** [comment]
It seems as though something has changed in the last couple weeks with the VS code version and now new file additions are not detected at all - even as excluded changes.  So when it comes time to check in new files are constantly being missed.
