### ISSUE TITLE
node_modules in conflicting changes

### ISSUE THREAD

**Issue by dineshbn** [microsoft/azure-repos-vscode#298]
I have included node_modules in Version control(Team service) and later deleted  from my version control(Team service). Then,i  included .tfignore in root of the project repository and add _\node_modules_ in it. but  source control in VSCODE still showing the all the node_modules files under conflicting changes section.

![image](https://user-images.githubusercontent.com/5179637/28905436-44814b0a-782e-11e7-8bca-ec7e4214e811.png)

while verifying the difference for excluded files  i am getting following error, because the files are already deleted from Team service.

![image](https://user-images.githubusercontent.com/5179637/28905458-6e4eb0d0-782e-11e7-80fb-8194d514701d.png)

**Comment by jeffyoung** [comment]
Thanks for trying out the extension @dineshbn.

The results being shown in the SCM Viewlet are those returned by tf.exe or the TEE CLC.  First, can you specify which one you're using?  That said, I believe the tf tool is actually returning unexpected results based on your .tfignore file.  Have you checked in the new .tfignore file by chance?  Also, what does the Visual Studio IDE render for this workspace (is the behavior the same there)?

I did find a **very long** GitHub issue in the aspnet repository about the .tfignore file not being respected (the issue was subsequently fixed).  However, I wonder if your issue might be addressed by what one user did in [this comment](https://github.com/aspnet/Tooling/issues/18#issuecomment-231772054).
