### ISSUE TITLE
New files not checking in into TFS.

### ISSUE THREAD

**Issue by decernosia** [microsoft/azure-repos-vscode#456]
We are noticing that any new files added to our VS Code project are not being checked into TFS (only previously checked-in items are synced up).

I tried looking for the new items under Source Control's EXCLUDED ITEMS, but the list is so ridiculously long because it includes every file under folders DIST and NODE_MODULES.   

Is there a way you can give us a feature to show only certain folders under EXCLUDED ITEMS ??

**Comment by andreaci** [comment]
Same as https://github.com/Microsoft/azure-repos-vscode/issues/362

**Comment by adam-marshall** [comment]
I think this may be different to #362.

This issue may really be _New files appear in 'excluded items' by default, instead of 'included items'_

I remedied this by using a .tfignore file to exclude all those kind of items, e.g.

![image](https://user-images.githubusercontent.com/2521384/65332279-433b4780-dbb6-11e9-8bbf-0db9e22e2376.png)

However since then, a new issue has emerged for me, which may be the same as #362 - the new files don't even appear in 'excluded changes' now, there is no way of adding them to source control via TFS at all.
