### ISSUE TITLE
Deprecated - Other Solutions for users?

### ISSUE THREAD

**Issue by aptMattKoe** [microsoft/azure-repos-vscode#643]
First of all: Thanks for that extension. 
I only used it half an year but enjoyed it!

But did anybody know how to "Create Pull Request" out of vs code?

**Comment by stevengibbszions** [comment]
Agreed. Loved the "Create Pull request" feature.  Also looking for alternatives.

**Comment by gregveres** [comment]
I use it every time I checkin to "Associate work items". Is there some other extension or work flow that does that now that this extension is going away?

**Comment by vrdse** [comment]
Looking for "Create Pull Request" feature, too.

**Comment by nrogoff** [comment]
Also like to thank you for this extension. I love it, and sad to see it go.

**Comment by Godrules500** [comment]
It's unfortunate to see this happen. A lot of us are already forced to use TFVC and this helped to at least make it a little less painful.

**Comment by Glober777** [comment]
I used the extension primarily with Git on Azure DevOps.

Apart from 'Create Pull Request' feature, I also got used to a shortcut to the team project website.

Is there a chance that everything that's not related to TFVC be migrated to a new extension, i.e. Azure DevOps?

**Comment by dandax** [comment]
Would be nice if there was something like the GitHub Pull Requests and Issues extension for Azure DevOps.

[https://github.com/microsoft/vscode-pull-request-github](https://github.com/microsoft/vscode-pull-request-github)

**Comment by arshia11d** [comment]
Yeah! Of course I agree that the use of TFVC has declined but I am using it with Git as Azure DevOps integration.
please consider keeping useful features of the extension tools.

Or even better, merge all useful features of all extensions to a lightweight Azure DevOps extension!

**Comment by willaaam** [comment]
Agree with what is said above. The create-pull-request is super handy. Also exclusively using it with Git.

So while I can imagine the business decision behind dropping TFVC, it's really hard to say goodbye to these QOL improvements for git.

**Comment by smaglio81** [comment]
I agree on "Create Pull Request" and would also add "View Build Summary" to the list of desirable features to reimplement elsewhere (Azure Pipelines?)

**Comment by abarmp** [comment]
Why is this being deprecated? I understand TFVC decline but what about git functionality and git pull requests on Azure DevOps?
Thank you

**Comment by aptMattKoe** [comment]
I realy hope that one developers sees this :(

**Comment by imivz** [comment]
I use this at work and im a bit scared and confused. What does this mean? Does it mean we can't use source control with git in vscode anymore or is it only TFVC or are we just screwed in general? Do we manually have to upload files to our Azure DevOps repos?

**Comment by CharlesNadolskiNtrs** [comment]
To answer your questions:
* You will be able to use git from within VS Code
* You will not be able to use TFVC from within VS Code
* Unknown if you can use SSO with Azure DevOps with Git repos.  I have to test this for my team :( I'm assuming the Azure Accounts extension with the Git Credential Manager will allow SSO. **Can somebody from Microsoft address this quest?**

**Comment by Volkmire** [comment]
@vtbassmatt , could you provide some clarifications? 

I don't think anyone uses the extension with TFVC and the decline in popularity could probably be attributed to the critical bugs in the extension that weren't fixed for years (2 pages of issues on the "team:SignIn" alone, ex: #371 ). I'm not sure how one can expect something to be popular if you can't even start using the bloody thing. :smile:

On the other hand, I can agree with the most folks - i don't really care about the SVC functionality, what i do care about is the project interaction features (create pull requests, build status (if i'd work correctly), work items etc).

Is it possible that you would reconsider complete deprecation, only remove TFVC support and re-purpose this extension as "Azure DevOps Team Project" or something?

It is really comfy (when it works).

**Comment by vtbassmatt** [comment]
Hey folks. Sorry, I didn't notice this thread until someone pinged me by name.

There isn't a lot more I can add, mostly because I don't have all the history on our (lack of) investment in the extension. When I picked up this project, it was already languishing. As you pointed out, bugs left unfixed for years lead to declining usage. I'm guessing that helped drive the decisions to pull back investment, a downward spiral that's hard to pull out of.

I'm going to spare you the sob story, the alternatives considered, and all that. There's simply no team available to pick this extension up again. I _will_ point out that the extension is [MIT licensed](https://github.com/microsoft/azure-repos-vscode/blob/master/LICENSE.txt) so other projects are free to use components if they'd like.

**Comment by vhhughes** [comment]
Hadn't ever been to this Github repo until now. We've had entire teams who have installed and been hoping to continue using this extension. The extension has had a bug we've all seen here for a while now that we hoped was being resolved. (It complains that we need to use TFVC Server workspaces when we are all already, in fact, using Server workspaces.) I'm immensely disappointed to see today that this is being retired. Yes, our use has gone down as we've be forced to use Visual Studio for managing TFVC check-ins, but it's only been because of the bug that's been present with this extension for so long. Really sad to see this waning support. We literally have hundreds of devs on our project and will continue to use TFVC into the future. Git-based repos (even larger ones) still just can't hold a candle to it for what we're doing. (features, performance, productivity, etc.) This extension had lots of promise.

**Comment by CharlesNadolskiNtrs** [comment]
> Hey folks. Sorry, I didn't notice this thread until someone pinged me by name.
> 
> There isn't a lot more I can add, mostly because I don't have all the history on our (lack of) investment in the extension. When I picked up this project, it was already languishing. As you pointed out, bugs left unfixed for years lead to declining usage. I'm guessing that helped drive the decisions to pull back investment, a downward spiral that's hard to pull out of.
> 
> I'm going to spare you the sob story, the alternatives considered, and all that. There's simply no team available to pick this extension up again. I _will_ point out that the extension is [MIT licensed](https://github.com/microsoft/azure-repos-vscode/blob/master/LICENSE.txt) so other projects are free to use components if they'd like.

Gee I wonder if somebody could fork this repo, rip out the TFVC broken stuff, and publish a new extension to the marketplace while also fulfilling the terms of the MIT license.
